#设置启用的环境
spring:
  profiles:
    active: ${profile.active}
---


spring:
  profiles: dev
server:
  port: 80
---


spring:
  profiles: pro
server:
  port: 81
---


spring:
  profiles: test
server:
  port: 82
